version: 2

updates:
  - package-ecosystem: 'bun'
    directory: '/'

    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Hong_Kong'

    groups:
      minor-and-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

    labels:
      - dependencies

    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directories:
      - '/'
      - '/.github/actions/*'

    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Hong_Kong'

    groups:
      minor-and-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

    labels:
      - dependencies

    open-pull-requests-limit: 10
