name: Setup
description: Install Node.js, pnpm and dependencies

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

    - name: Build MDX
      shell: bash
      run: pnpm build:mdx

    - name: Build Cosmos
      shell: bash
      run: pnpm cosmos:export

    - name: Generate Next.js route types
      shell: bash
      run: pnpm typegen
