name: Setup
description: Install Bun and dependencies

runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.0

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install dependencies
      shell: bash
      run: bun install
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
